---
title: "Previous Projects"
navbar:
  title: Wenxin Yang
  left:
  - text: Home
    href: index.html
  - text: Projects
    href: projects.html
  - text: Photos
    href: about.html

---
-------------------------------------------------------------------------------

__Web-based data visualization__

* Visualization of [car crashes in Boston](https://wxyang007.github.io/datavizmusa620/MUSA620_final/): done with Jupyter Notebook and generated through GitHub Page


<br>

__Done with R__

* [Chicago Food Inspection](musa507final.html): designing a toolkit to predict food inspection failure in Chicago


* [Urban Gardening & Twitter Data](https://drive.google.com/file/d/1e8l0Jd63YBEMhyl_kCfKUU-txfJUl5X7/view?usp=sharing)


<br>


__Done with ArcMap/ArcPy__

* ArcMap: [Using Remote Sensing to Depict Urban Growth in Beijing](https://drive.google.com/file/d/11ozqnC0L43qK7s1oA31ukD345YNP5w_E/view?usp=sharing)

* ArcPy: [Creating Tools to Map Inundation Using Data from SLOSH Program](https://drive.google.com/open?id=17MmY-m2rLA75zV4NcUpxYbIfEhfrEr0M)

* ArcMap & Python: My current capstone project about Preserved Farmland in Lancaster County



<br>


__Done with Python__

* [Analyzing Yelp Reviews of Restaurants in Pittsburgh](yelp.html)



<br>


__Done with JavaScript__

* Trough Google Earth Engine: A simple play-around with an online dataset to [Visualize Precipitation Change](https://drive.google.com/file/d/1ds8HpX7YqJvhhdkAaZpFBrAT_2koqJWp/view?usp=sharing)
* Through Observable: An interactive map of [when properties were built in Philadelphia](https://observablehq.com/@wenxinyang/musa620-assignment6-part-ii)
